baseURL = "https://www.pushingthestack.com/"
googleAnalytics = "UA-127162666-1"
languageCode = "en-us"
title = "Pushing the Stack"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength = 50
pluralizelisttitles = false

[menu]
  [[menu.main]]
    identifier = "javascript"
    name = "JavaScript"
    pre = "<i class='fa fa-bolt'></i>"
    url = "/javascript/"
    weight = -110
  [[menu.main]]
    identifier = "devops"
    name = "Devops"
    pre = "<i class='fa fa-road'></i>"
    url = "/devops/"
    weight = -100
